In [1]:
import numpy as np

In [3]:
#1-d Array
arr1=np.array([1,2,3,4,5])
     

arr1

array([1, 2, 3, 4, 5])

In [5]:
type(arr1)
     

numpy.ndarray

In [7]:
print(arr1.ndim)
     

1


In [9]:
#2-d Array
arr2=np.array([[1,2,3],[4,5,6]])

In [11]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
print(arr2.ndim)


2


In [15]:
arr3=np.zeros((2,3))
     

arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
arr4=np.ones((3,3))
     

arr4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [19]:
# 0-d Array
arr=np.array(55)
arr

array(55)

In [21]:
# Accessing Array Elements
arr1=np.array([1,2,3,4,5])

print(arr1[0])
     

1


In [23]:
import numpy as np

arr3 = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr3[1:5])

[2 3 4 5]


In [25]:
arr4 = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr4[4:])
     

[5 6 7]


In [27]:
arr5 = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr5[:4])
     

[1 2 3 4]


In [29]:

arr6 = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr6[-3:-1])
     

[5 6]


In [31]:
#Reshape From 1-D to 2-D
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)
     

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [33]:
# Reshape From 1-D to 3-D
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)
     

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [35]:
# Iterating Arrays
arr = np.array([1, 2, 3])

for x in arr:
  print(x)
     


1
2
3


In [37]:
# Iterate on the elements of the following 2-D array:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)
     

[1 2 3]
[4 5 6]


In [39]:
# NumPy Joining Array
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)
     


[1 2 3 4 5 6]


In [41]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2),axis=1)

print(arr)
     

[[1 2 5 6]
 [3 4 7 8]]


In [43]:
# Join two 2-D arrays along rows (axis=1):
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)
     

[[1 2 5 6]
 [3 4 7 8]]


In [45]:
#Splitting NumPy Arrays
# Splitting is reverse operation of Joining.

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)
     

[array([1, 2]), array([3, 4]), array([5, 6])]


In [47]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [49]:
# Random Numbers
# NumPy offers the random module to work with random numbers.
# Generate a random integer from 0 to 100:
from numpy import random

x = random.randint(100)

print(x)
     

29


In [51]:
# Random module's rand() method returns a random float between 0 and 1.
from numpy import random

x = random.rand()

print(x)

0.5467757931286706


In [53]:
# Generate Random Array
from numpy import random

x=random.randint(100, size=(5))

print(x)

[95 81 67 47 37]


In [55]:
# A 2-D array with 3 rows, each row containing 5 random integers from 0 to 100:

from numpy import random

x = random.randint(100, size=(3, 5))

print(x)
     

[[90 72  4 88 43]
 [22 93 39 39 78]
 [65  1 88 36 93]]


In [57]:
# Generate a 1-D array containing 5 random floats:
from numpy import random

x = random.rand(5)

print(x)
     

[0.85873649 0.35303081 0.48350269 0.15555003 0.16005566]
