In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))


[1 2 3 4 5]
<class 'numpy.ndarray'>


In [5]:
import numpy as np

arr = np.array(42)

print(arr)

42


In [7]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [9]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


In [11]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [13]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [15]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)


[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [1]:
  import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:])


[5 6 7]


In [5]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])


[5 6]


In [7]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])


[2 4]


In [9]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::2])

[1 3 5 7]


In [11]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


In [13]:
#Get the data type of an array object:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int32


In [15]:
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [19]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[1] = 42

print(arr)
print(x)


[ 1 42  3  4  5]
[1 2 3 4 5]


In [52]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)


[1 2 3 4 5]
[1 2 3 4 5]


In [23]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)


(2, 4)


In [30]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)


[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [32]:
import numpy as np
arr = np.array([21,23,24,45,],ndmin=6)

print(arr)
print('shape of array :', arr.shape)

[[[[[[21 23 24 45]]]]]]
shape of array : (1, 1, 1, 1, 1, 4)


In [40]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(6, 2)

print(newarr)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [42]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [48]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(4, 2)

print(newarr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [7]:
import numpy as np

arr = np.array([1, 2, 3])

for x in arr:
  print(x)


1
2
3


In [9]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [11]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


In [13]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [15]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [17]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [19]:
import numpy as np 
arr = np.array([12,13,14,14,14,14,17,17])
newarr = np.array_split(arr,3)
print(newarr)

[array([12, 13, 14]), array([14, 14, 14]), array([17, 17])]


In [21]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [23]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6], dtype=int64),)


In [25]:
import  numpy as np
arr = np.array([12,13,13,14,14,14,15,15,14,14,])
y = np.where(arr ==14)
print(y)


(array([3, 4, 5, 8, 9], dtype=int64),)


In [27]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 7], dtype=int64),)


In [29]:
import numpy as np

arr = np.array([3, 2, 0, 1])

print(np.sort(arr))


[0 1 2 3]


In [33]:
import numpy as np
arr = np.array([9,8,7,6,5,4,3,2,1])
print(np.sort(arr))

[1 2 3 4 5 6 7 8 9]


In [35]:
import numpy as np

arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))


[[2 3 4]
 [0 1 5]]


In [37]:
import numpy as np

arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)

[41 43]


In [41]:
from numpy import random

x = random.randint(100)

print(x)

87


In [45]:
from numpy import random
x = random.randint(10)
print(x)

9


In [51]:
from numpy import random

x = random.rand()

print(x)

0.11011203305486517


In [53]:
from numpy import random

x=random.randint(100, size=(5))

print(x)

[88 78 48 34 21]


In [55]:
from numpy import random

x = random.randint(100, size=(3, 5))

print(x)

[[58 47 72 15 12]
 [38  1 34 11  2]
 [96 20 64 47 49]]


In [57]:
import numpy as np

np.arange(1, 20 , 2, 
          dtype = np.float32)

array([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19.], dtype=float32)

In [59]:
import numpy as np

np.linspace(3.5, 10, 3, 
            dtype = np.int32)

array([ 3,  6, 10])

In [69]:
import numpy as np

np.empty([4, 3],
         dtype = np.int32,
         order = 'f')

array([[4128860, 6619251, 5636175],
       [6029375, 7536754, 6029391],
       [3801155, 4980828, 7340097],
       [5570652, 5111877, 4456560]])

In [75]:
import numpy as np

np.ones([4, 3],
        dtype = np.int32,
        order = 'f')

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

def 